<a href="https://www.kaggle.com/code/aleksandr13254/mysolve?scriptVersionId=109394925" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from tqdm import tqdm # loops show a smart progress meter
from sklearn import preprocessing
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
import torch
import torch.nn as nn
import copy
import plotly.graph_objects as go
import plotly.express as px

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/dataset-cpi-test/CPI_MoM.csv
/kaggle/input/dataset-cpi-test/CPI_YoY.csv
/kaggle/input/dataset-cpi-test/CPI_Russia.csv
/kaggle/input/dataset-cpi-test/Product_Price_Month.csv
/kaggle/input/dataset-cpi-test/Product_Price_Day.csv
/kaggle/input/dataset-cpi-test/Product_CPI.csv
/kaggle/input/dataset/DS_tests/DS_test9(2020-06--2022-09-01).csv
/kaggle/input/dataset/DS_tests/DS_test8(2020-06--2022-08-21).csv
/kaggle/input/dataset/DS_tests/DS_test5(2020-06--2022-07-21).csv
/kaggle/input/dataset/DS_tests/DS_test4(2020-06--2022-07-11).csv
/kaggle/input/dataset/DS_tests/DS_test7(2020-06--2022-08-11).csv
/kaggle/input/dataset/DS_tests/DS_test1(2020-06--2022-06-11).csv
/kaggle/input/dataset/DS_tests/DS_test3(2020-06--2022-07-01).csv
/kaggle/input/dataset/DS_tests/DS_test6(2020-06--2022-08-01).csv
/kaggle/input/dataset/DS_tests/DS_test2(2020-06--2022-06-21).csv
/kaggle/input/dataset/DS_train/DS_train(2020-06--2022-06-01).csv


In [ ]:
df = pd.read_csv('../input/dataset/DS_tests/DS_test9(2020-06--2022-09-01).csv', delimiter='\t',parse_dates=['DateObserve'])
# df = pd.read_csv('../input/dataset/DS_train/DS_train(2020-06--2022-06-01).csv', delimiter='\t',parse_dates=['DateObserve'], nrows=107892)
df

In [ ]:
df = df[df['StockStatus']=='InStock'][['WebPriceId','DateObserve','CurrentPrice']]
df

In [ ]:
df.dropna()
df

In [ ]:
df['DateObserve'] = pd.to_datetime(df['DateObserve']).apply(lambda x: x.strftime('%Y-%m-%d'))
df

In [ ]:
df = df.groupby(['WebPriceId','DateObserve']).agg({'CurrentPrice': ['mean']}).reset_index()
df.columns = ['Id','Date','Price']
df

In [ ]:
df = df[df['Price'] < 100000]
df

In [ ]:
df = df[df['Price'] > 10]
df

In [ ]:
count_filtered = df.groupby(['Id'])['Id'].count()
count_filtered

In [ ]:
filtered_ids = pd.DataFrame(count_filtered[count_filtered > 60].index)
filtered_ids

In [ ]:
df = filtered_ids.merge(df, on='Id',how='inner')
df

In [ ]:
df.to_csv('Product_Price_Day.csv',sep=';',encoding='utf-8')
# df = pd.read_csv('../input/dataset-cpi-test/Product_Price_Day.csv', delimiter=';', index_col=[0])
df

In [ ]:
df['Date'] = pd.to_datetime(df['Date']).apply(lambda x: x.strftime('%Y-%m'))
df

In [ ]:
df = df.groupby(['Id','Date']).agg({'Price': ['mean']}).reset_index()
df.columns = ['Id','Date','Price']
df

In [ ]:
df.to_csv('Product_Price_Month.csv',sep=';',encoding='utf-8')
# df = pd.read_csv('../input/dataset-cpi-test/Product_Price_Month.csv', delimiter=';', index_col=[0])
df

In [ ]:
date_list_all = df.sort_values(by=['Date']).Date.unique()
date_list_all

In [ ]:
id_product_list = df['Id'].unique()[:-1]
len(id_product_list)

In [ ]:
id_list = list()
date_start_list = list()
date_end_list = list()
cpi_product_list = list()
for id_product in tqdm(id_product_list):
    df_id_product = df.loc[df.Id == id_product]
    date_list = df_id_product.sort_values(by=['Date']).Date.unique()
    for i in range(0, len(date_list)):        
        start_value = df_id_product.loc[df_id_product.Date == date_list[i]].Price.values[0]
        for j in range(i+1, len(date_list)):
            end_value = df_id_product.loc[df_id_product.Date == date_list[j]].Price.values[0]
            cpi_product = end_value/start_value*100
            id_list.append(id_product)
            date_start_list.append(date_list[i])
            date_end_list.append(date_list[j])
            cpi_product_list.append(cpi_product)

In [ ]:
cpi_id_product = pd.DataFrame({'Id': id_list, 'Date_start': date_start_list, 'Date_end': date_end_list, 'CPI': cpi_product_list})
cpi_id_product

In [ ]:
cpi_id_product.to_csv('Product_CPI.csv',sep=';',encoding='utf-8')
# cpi_id_product = pd.read_csv('../input/dataset-cpi-test/Product_CPI.csv', delimiter=';', index_col=[0])
cpi_id_product

In [ ]:
cpi_id_product = cpi_id_product[cpi_id_product.CPI < 120][cpi_id_product.CPI > 80]
cpi_id_product

In [ ]:
cpi_count = cpi_id_product[['Id','Date_start','Date_end',]].groupby(['Date_end','Date_start']).count().reset_index()
cpi_count.columns = ['Date_end','Date_start','Count_Id',]
cpi_count

In [ ]:
date_list_year = ['2020', '2021', '2022']
date_list_month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
date_list_year_month = list()
cpi_list = list()
cpi_date_list = list()
for y in date_list_year:
    for m in date_list_month:
        date_list_year_month.append(f'{y}-{m}')
for i in range(1, len(date_list_year_month)):
    item = cpi_count.loc[(cpi_count.Date_start == date_list_year_month[i-1]) & (cpi_count.Date_end == date_list_year_month[i])]
    if item.empty == False:
        cpi_list.append(item.Count_Id.values[0])
        cpi_date_list.append(item.Date_end.values[0])
cpi_id_count = pd.DataFrame({'Date': cpi_date_list, 'Count_Id': cpi_list})
cpi_id_count

In [ ]:
cpi_df = cpi_id_product.groupby(['Date_start','Date_end']).agg({'CPI': ['mean']}).reset_index()
cpi_df.columns = ['Date_start','Date_end','CPI']
cpi_df

In [ ]:
date_list_year = ['2020', '2021', '2022']
date_list_month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
date_list_year_month = list()
cpi_list = list()
cpi_date_list = list()
for y in date_list_year:
    for m in date_list_month:
        date_list_year_month.append(f'{y}-{m}')
for i in range(1, len(date_list_year_month)):
    item = cpi_df.loc[(cpi_df.Date_start == date_list_year_month[i-1]) & (cpi_df.Date_end == date_list_year_month[i])]
    if item.empty == False:
        cpi_list.append(item.CPI.values[0])
        cpi_date_list.append(item.Date_end.values[0])
cpi_mom = pd.DataFrame({'Date': cpi_date_list, 'MoM': cpi_list})
cpi_mom

In [ ]:
cpi_yoy = cpi_mom.copy()
for i in range(12, len(cpi_yoy)):
  temp = 100
  for j in range(11, -1, -1):
    temp *= float(cpi_mom.iloc[i-j, 1])/100
  cpi_yoy.iloc[i, 1] = temp
cpi_yoy = cpi_yoy.iloc[12:, :].reset_index(drop = True)
cpi_yoy.columns = ['Date','YoY']
cpi_yoy

In [2]:
# cpi_mom.to_csv('CPI_MoM.csv',sep=';',encoding='utf-8')
cpi_mom = pd.read_csv('../input/dataset-cpi-test/CPI_MoM.csv', delimiter=';', index_col=[0])
cpi_mom

Date         MoM
0   2020-07   99.851962
1   2020-08   99.337024
2   2020-09  100.570486
3   2020-10   99.910327
4   2020-11   97.395858
5   2020-12  101.445817
6   2021-01  101.144785
7   2021-02   99.449539
8   2021-03   99.582982
9   2021-04   99.711704
10  2021-05  100.894241
11  2021-06   98.932025
12  2021-07  100.771324
13  2021-08   99.910265
14  2021-09  101.387850
15  2021-10  103.915668
16  2021-11  102.798455
17  2021-12  101.004126
18  2022-01  102.137140
19  2022-02  100.120816
20  2022-03  106.746746
21  2022-04   97.438199
22  2022-05   97.832254
23  2022-06   98.473673
24  2022-07   99.243480
25  2022-08   99.716424

In [3]:
# cpi_yoy.to_csv('CPI_YoY.csv',sep=';',encoding='utf-8')
cpi_yoy = pd.read_csv('../input/dataset-cpi-test/CPI_YoY.csv', delimiter=';', index_col=[0])
cpi_yoy = cpi_yoy.iloc[:,1:].reset_index(drop = True)
cpi_yoy

YoY
0    99.079655
1    99.651411
2   100.461306
3   104.488735
4   110.284777
5   109.804602
6   110.881921
7   111.630367
8   119.660790
9   116.932430
10  113.383708
11  112.858401
12  111.147299
13  110.931656

In [4]:
cpi_russia = pd.read_csv('../input/dataset-cpi-test/CPI_Russia.csv', delimiter=';')
cpi_russia = cpi_russia
cpi_russia

Date  Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY
0   2020-07      100.35      103.37   100.36   103.25  100.48  103.92
1   2020-08       99.96      103.58    99.87   103.42  100.02  104.48
2   2020-09       99.93      103.67    99.89   103.48   99.86  104.44
3   2020-10      100.43      103.99   100.38   103.78  100.56  105.06
4   2020-11      100.71      104.42   100.65   104.16  100.73  105.43
5   2020-12      100.83      104.91   100.84   104.70  100.82  105.79
6   2021-01      100.67      105.19   100.79   105.11  101.00  106.34
7   2021-02      100.78      105.67   100.71   105.55  101.03  106.99
8   2021-03      100.66      105.79   100.63   105.71  100.58  106.64
9   2021-04      100.58      105.53   100.54   105.54  100.78  106.53
10  2021-05      100.74      106.02   100.82   105.97  100.88  107.20
11  2021-06      100.69      106.50   100.74   106.40  100.77  107.76
12  2021-07      100.31      106.46   100.26   106.30  100.31  107.57
13  2021-08      100.17      106.68   100.10   106.53  100.29  107.87
14  2021-09      100.60      107.40   100.66   107.35  100.53  108.60
15  2021-10      101.11      108.13   101.02   108.03  101.51  109.63
16  2021-11      100.96      108.40   100.96   108.36  100.86  109.77
17  2021-12      100.82      108.39   100.80   108.32  100.97  109.94
18  2022-01      100.99      108.73   100.96   108.50  101.22  110.18
19  2022-02      101.17      109.15   101.42   109.26  101.13  110.28
20  2022-03      107.61      116.69   107.37   116.58  109.02  119.54
21  2022-04      101.56      117.83   101.74   117.97  102.40  121.46
22  2022-05      100.12      117.10   100.23   117.29  100.01  120.41
23  2022-06       99.65      115.90    99.91   116.32   99.73  119.17
24  2022-07       99.61      115.10    99.57   115.52   99.34  118.02
25  2022-08       99.48      114.30    99.55   114.89   99.24  116.78

In [5]:
df_14 = pd.concat([cpi_russia.iloc[12:,1:].reset_index(drop = True), cpi_mom.iloc[12:,1:].reset_index(drop = True), cpi_yoy], axis=1)
df_14

Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY         MoM  \
0       100.31      106.46   100.26   106.30  100.31  107.57  100.771324   
1       100.17      106.68   100.10   106.53  100.29  107.87   99.910265   
2       100.60      107.40   100.66   107.35  100.53  108.60  101.387850   
3       101.11      108.13   101.02   108.03  101.51  109.63  103.915668   
4       100.96      108.40   100.96   108.36  100.86  109.77  102.798455   
5       100.82      108.39   100.80   108.32  100.97  109.94  101.004126   
6       100.99      108.73   100.96   108.50  101.22  110.18  102.137140   
7       101.17      109.15   101.42   109.26  101.13  110.28  100.120816   
8       107.61      116.69   107.37   116.58  109.02  119.54  106.746746   
9       101.56      117.83   101.74   117.97  102.40  121.46   97.438199   
10      100.12      117.10   100.23   117.29  100.01  120.41   97.832254   
11       99.65      115.90    99.91   116.32   99.73  119.17   98.473673   
12       99.61      115.10    99.57   115.52   99.34  118.02   99.243480   
13       99.48      114.30    99.55   114.89   99.24  116.78   99.716424   

           YoY  
0    99.079655  
1    99.651411  
2   100.461306  
3   104.488735  
4   110.284777  
5   109.804602  
6   110.881921  
7   111.630367  
8   119.660790  
9   116.932430  
10  113.383708  
11  112.858401  
12  111.147299  
13  110.931656

In [6]:
df_13_mom = df_14.iloc[:,[0,-2,-1]].copy()
df_13_mom['Russia_MoM-1'] = df_14['Russia_MoM'].shift(1)
df_13_mom['Russia_YoY-1'] = df_14['Russia_YoY'].shift(1)
df_13_mom = df_13_mom.iloc[1:,:].reset_index(drop = True)
df_13_mom

Russia_MoM         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0       100.17   99.910265   99.651411        100.31        106.46
1       100.60  101.387850  100.461306        100.17        106.68
2       101.11  103.915668  104.488735        100.60        107.40
3       100.96  102.798455  110.284777        101.11        108.13
4       100.82  101.004126  109.804602        100.96        108.40
5       100.99  102.137140  110.881921        100.82        108.39
6       101.17  100.120816  111.630367        100.99        108.73
7       107.61  106.746746  119.660790        101.17        109.15
8       101.56   97.438199  116.932430        107.61        116.69
9       100.12   97.832254  113.383708        101.56        117.83
10       99.65   98.473673  112.858401        100.12        117.10
11       99.61   99.243480  111.147299         99.65        115.90
12       99.48   99.716424  110.931656         99.61        115.10

In [7]:
df_13_yoy = df_14.iloc[:,[1,-2,-1]].copy()
df_13_yoy['Russia_MoM-1'] = df_14['Russia_MoM'].shift(1)
df_13_yoy['Russia_YoY-1'] = df_14['Russia_YoY'].shift(1)
df_13_yoy = df_13_yoy.iloc[1:,:].reset_index(drop = True)
df_13_yoy

Russia_YoY         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0       106.68   99.910265   99.651411        100.31        106.46
1       107.40  101.387850  100.461306        100.17        106.68
2       108.13  103.915668  104.488735        100.60        107.40
3       108.40  102.798455  110.284777        101.11        108.13
4       108.39  101.004126  109.804602        100.96        108.40
5       108.73  102.137140  110.881921        100.82        108.39
6       109.15  100.120816  111.630367        100.99        108.73
7       116.69  106.746746  119.660790        101.17        109.15
8       117.83   97.438199  116.932430        107.61        116.69
9       117.10   97.832254  113.383708        101.56        117.83
10      115.90   98.473673  112.858401        100.12        117.10
11      115.10   99.243480  111.147299         99.65        115.90
12      114.30   99.716424  110.931656         99.61        115.10

In [8]:
df_26 = pd.concat([cpi_russia.iloc[:,1:], cpi_mom.iloc[:,1:]], axis=1)
df_26

Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY         MoM
0       100.35      103.37   100.36   103.25  100.48  103.92   99.851962
1        99.96      103.58    99.87   103.42  100.02  104.48   99.337024
2        99.93      103.67    99.89   103.48   99.86  104.44  100.570486
3       100.43      103.99   100.38   103.78  100.56  105.06   99.910327
4       100.71      104.42   100.65   104.16  100.73  105.43   97.395858
5       100.83      104.91   100.84   104.70  100.82  105.79  101.445817
6       100.67      105.19   100.79   105.11  101.00  106.34  101.144785
7       100.78      105.67   100.71   105.55  101.03  106.99   99.449539
8       100.66      105.79   100.63   105.71  100.58  106.64   99.582982
9       100.58      105.53   100.54   105.54  100.78  106.53   99.711704
10      100.74      106.02   100.82   105.97  100.88  107.20  100.894241
11      100.69      106.50   100.74   106.40  100.77  107.76   98.932025
12      100.31      106.46   100.26   106.30  100.31  107.57  100.771324
13      100.17      106.68   100.10   106.53  100.29  107.87   99.910265
14      100.60      107.40   100.66   107.35  100.53  108.60  101.387850
15      101.11      108.13   101.02   108.03  101.51  109.63  103.915668
16      100.96      108.40   100.96   108.36  100.86  109.77  102.798455
17      100.82      108.39   100.80   108.32  100.97  109.94  101.004126
18      100.99      108.73   100.96   108.50  101.22  110.18  102.137140
19      101.17      109.15   101.42   109.26  101.13  110.28  100.120816
20      107.61      116.69   107.37   116.58  109.02  119.54  106.746746
21      101.56      117.83   101.74   117.97  102.40  121.46   97.438199
22      100.12      117.10   100.23   117.29  100.01  120.41   97.832254
23       99.65      115.90    99.91   116.32   99.73  119.17   98.473673
24       99.61      115.10    99.57   115.52   99.34  118.02   99.243480
25       99.48      114.30    99.55   114.89   99.24  116.78   99.716424

In [9]:
df_25 = df_26.iloc[:,[0,-1]].copy()
df_25['Russia_MoM-1'] = df_26['Russia_MoM'].shift(1)
df_25 = df_25.iloc[1:,:].reset_index(drop = True)
df_25

Russia_MoM         MoM  Russia_MoM-1
0        99.96   99.337024        100.35
1        99.93  100.570486         99.96
2       100.43   99.910327         99.93
3       100.71   97.395858        100.43
4       100.83  101.445817        100.71
5       100.67  101.144785        100.83
6       100.78   99.449539        100.67
7       100.66   99.582982        100.78
8       100.58   99.711704        100.66
9       100.74  100.894241        100.58
10      100.69   98.932025        100.74
11      100.31  100.771324        100.69
12      100.17   99.910265        100.31
13      100.60  101.387850        100.17
14      101.11  103.915668        100.60
15      100.96  102.798455        101.11
16      100.82  101.004126        100.96
17      100.99  102.137140        100.82
18      101.17  100.120816        100.99
19      107.61  106.746746        101.17
20      101.56   97.438199        107.61
21      100.12   97.832254        101.56
22       99.65   98.473673        100.12
23       99.61   99.243480         99.65
24       99.48   99.716424         99.61

In [10]:
scaler = preprocessing.StandardScaler()
names = df_25.columns
df_25_norm = pd.DataFrame(scaler.fit_transform(df_25), columns=names)
df_25_norm

Russia_MoM       MoM  Russia_MoM-1
0    -0.572304 -0.527321     -0.336815
1    -0.592608  0.087555     -0.604673
2    -0.254207 -0.241532     -0.625278
3    -0.064702 -1.494985     -0.281869
4     0.016514  0.523904     -0.089561
5    -0.091774  0.373840     -0.007143
6    -0.017326 -0.471233     -0.117034
7    -0.098542 -0.404712     -0.041484
8    -0.152687 -0.340545     -0.123902
9    -0.044398  0.248945     -0.178847
10   -0.078238 -0.729212     -0.068956
11   -0.335423  0.187672     -0.103297
12   -0.430176 -0.241563     -0.364287
13   -0.139151  0.495008     -0.460442
14    0.206019  1.755115     -0.165111
15    0.104498  1.198189      0.185166
16    0.009746  0.303723      0.082143
17    0.124802  0.868526     -0.014011
18    0.246627 -0.136604      0.102748
19    4.605235  3.166397      0.226375
20    0.510580 -1.473878      4.649473
21   -0.464016 -1.277444      0.494233
22   -0.782113 -0.957699     -0.494783
23   -0.809185 -0.573953     -0.817586
24   -0.897169 -0.338192     -0.845059

In [11]:
df_25_norm_train = df_25_norm.iloc[:-3]
df_25_norm_test = df_25_norm.iloc[-3:]
gb_25 = GradientBoostingRegressor(n_estimators = 200, max_depth = 3)
gb_25.fit(df_25_norm_train.iloc[:, 1:], df_25_norm_train.iloc[:, 0])
df_25_gb_predict = gb_25.predict(df_25_norm.iloc[:, 1:])
df_25_gb_predict

array([-0.57165984, -0.59216484, -0.25425537, -0.06493963,  0.01671039,
       -0.09092903, -0.01830373, -0.0978253 , -0.15202693, -0.04509012,
       -0.07874059, -0.3349132 , -0.43046644, -0.13929548,  0.20611315,
        0.10489401,  0.00947239,  0.12396665,  0.24596516,  4.6048977 ,
        0.51050351, -0.46344519, -0.51831244, -0.39634055, -0.32921356])

In [12]:
gb_25.feature_importances_

array([0.95156223, 0.04843777])

In [13]:
df_25_norm_gb = pd.DataFrame({'Russia_MoM_predict': df_25_gb_predict, 'MoM': df_25_norm.iloc[:, 1], 'Russia_MoM-1': df_25_norm.iloc[:, 2]})
df_25_norm_gb

Russia_MoM_predict       MoM  Russia_MoM-1
0            -0.571660 -0.527321     -0.336815
1            -0.592165  0.087555     -0.604673
2            -0.254255 -0.241532     -0.625278
3            -0.064940 -1.494985     -0.281869
4             0.016710  0.523904     -0.089561
5            -0.090929  0.373840     -0.007143
6            -0.018304 -0.471233     -0.117034
7            -0.097825 -0.404712     -0.041484
8            -0.152027 -0.340545     -0.123902
9            -0.045090  0.248945     -0.178847
10           -0.078741 -0.729212     -0.068956
11           -0.334913  0.187672     -0.103297
12           -0.430466 -0.241563     -0.364287
13           -0.139295  0.495008     -0.460442
14            0.206113  1.755115     -0.165111
15            0.104894  1.198189      0.185166
16            0.009472  0.303723      0.082143
17            0.123967  0.868526     -0.014011
18            0.245965 -0.136604      0.102748
19            4.604898  3.166397      0.226375
20            0.510504 -1.473878      4.649473
21           -0.463445 -1.277444      0.494233
22           -0.518312 -0.957699     -0.494783
23           -0.396341 -0.573953     -0.817586
24           -0.329214 -0.338192     -0.845059

In [14]:
df_25_gb = pd.DataFrame(scaler.inverse_transform(df_25_norm_gb), columns=df_25_norm_gb.columns)
df_25_gb

Russia_MoM_predict         MoM  Russia_MoM-1
0            99.960952   99.337024        100.35
1            99.930655  100.570486         99.96
2           100.429929   99.910327         99.93
3           100.709649   97.395858        100.43
4           100.830290  101.445817        100.71
5           100.671249  101.144785        100.83
6           100.778556   99.449539        100.67
7           100.661060   99.582982        100.78
8           100.580975   99.711704        100.66
9           100.738978  100.894241        100.58
10          100.689258   98.932025        100.74
11          100.310754  100.771324        100.69
12          100.169570   99.910265        100.31
13          100.599786  101.387850        100.17
14          101.110140  103.915668        100.60
15          100.960585  102.798455        101.11
16          100.819596  101.004126        100.96
17          100.988765  102.137140        100.82
18          101.169022  100.120816        100.99
19          107.609502  106.746746        101.17
20          101.559887   97.438199        107.61
21          100.120843   97.832254        101.56
22          100.039775   98.473673        100.12
23          100.219993   99.243480         99.65
24          100.319175   99.716424         99.61

In [15]:
df_25_norm_train = df_25_norm.iloc[:-3]
df_25_norm_test = df_25_norm.iloc[-3:]
rf_25 = RandomForestRegressor(n_estimators = 100, max_depth = 9)
rf_25.fit(df_25_norm_train.iloc[:, 1:], df_25_norm_train.iloc[:, 0])
df_25_rf_predict = rf_25.predict(df_25_norm.iloc[:, 1:])
df_25_rf_predict

array([-0.46712906, -0.44817859, -0.35227568, -0.16087594, -0.04033743,
       -0.06338255, -0.08338206, -0.1036523 , -0.13129968, -0.06734184,
       -0.11532714, -0.22273569, -0.41521831, -0.23661014,  0.13569889,
        0.2158323 ,  0.01813831,  0.08128398,  0.07201178,  2.82788371,
        0.4292958 , -0.04615793, -0.41663959, -0.38225803, -0.34564302])

In [16]:
rf_25.feature_importances_

array([0.68407868, 0.31592132])

In [17]:
df_25_norm_rf = pd.DataFrame({'Russia_MoM_predict': df_25_rf_predict, 'MoM': df_25_norm.iloc[:, 1], 'Russia_MoM-1': df_25_norm.iloc[:, 2]})
df_25_norm_rf

Russia_MoM_predict       MoM  Russia_MoM-1
0            -0.467129 -0.527321     -0.336815
1            -0.448179  0.087555     -0.604673
2            -0.352276 -0.241532     -0.625278
3            -0.160876 -1.494985     -0.281869
4            -0.040337  0.523904     -0.089561
5            -0.063383  0.373840     -0.007143
6            -0.083382 -0.471233     -0.117034
7            -0.103652 -0.404712     -0.041484
8            -0.131300 -0.340545     -0.123902
9            -0.067342  0.248945     -0.178847
10           -0.115327 -0.729212     -0.068956
11           -0.222736  0.187672     -0.103297
12           -0.415218 -0.241563     -0.364287
13           -0.236610  0.495008     -0.460442
14            0.135699  1.755115     -0.165111
15            0.215832  1.198189      0.185166
16            0.018138  0.303723      0.082143
17            0.081284  0.868526     -0.014011
18            0.072012 -0.136604      0.102748
19            2.827884  3.166397      0.226375
20            0.429296 -1.473878      4.649473
21           -0.046158 -1.277444      0.494233
22           -0.416640 -0.957699     -0.494783
23           -0.382258 -0.573953     -0.817586
24           -0.345643 -0.338192     -0.845059

In [18]:
df_25_rf = pd.DataFrame(scaler.inverse_transform(df_25_norm_rf), columns=df_25_norm_rf.columns)
df_25_rf

Russia_MoM_predict         MoM  Russia_MoM-1
0            100.11540   99.337024        100.35
1            100.14340  100.570486         99.96
2            100.28510   99.910327         99.93
3            100.56790   97.395858        100.43
4            100.74600  101.445817        100.71
5            100.71195  101.144785        100.83
6            100.68240   99.449539        100.67
7            100.65245   99.582982        100.78
8            100.61160   99.711704        100.66
9            100.70610  100.894241        100.58
10           100.63520   98.932025        100.74
11           100.47650  100.771324        100.69
12           100.19210   99.910265        100.31
13           100.45600  101.387850        100.17
14           101.00610  103.915668        100.60
15           101.12450  102.798455        101.11
16           100.83240  101.004126        100.96
17           100.92570  102.137140        100.82
18           100.91200  100.120816        100.99
19           104.98390  106.746746        101.17
20           101.43990   97.438199        107.61
21           100.73740   97.832254        101.56
22           100.19000   98.473673        100.12
23           100.24080   99.243480         99.65
24           100.29490   99.716424         99.61

In [19]:
scaler = preprocessing.StandardScaler()
names = df_13_mom.columns
df_13_norm = pd.DataFrame(scaler.fit_transform(df_13_mom), columns=names)
df_13_norm

Russia_MoM       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0    -0.448931 -0.365105 -1.907280     -0.418912     -1.111940
1    -0.233336  0.224650 -1.760327     -0.490500     -1.060631
2     0.022369  1.233588 -1.029559     -0.270621     -0.892710
3    -0.052838  0.787670  0.022118     -0.009834     -0.722456
4    -0.123032  0.071492 -0.065008     -0.086536     -0.659486
5    -0.037797  0.523717  0.130469     -0.158124     -0.661818
6     0.052452 -0.281067  0.266272     -0.071195     -0.582522
7     3.281359  2.363568  1.723373      0.020847     -0.484568
8     0.247992 -1.351791  1.228319      3.313926      1.273941
9    -0.474000 -1.194510  0.584412      0.220273      1.539817
10   -0.709650 -0.938498  0.489096     -0.516068      1.369563
11   -0.729705 -0.631242  0.178621     -0.756401      1.089694
12   -0.794885 -0.442473  0.139493     -0.776855      0.903115

In [20]:
df_13_norm_train = df_13_norm.iloc[:-3]
df_13_norm_test = df_13_norm.iloc[-3:]
gb_13 = GradientBoostingRegressor(n_estimators = 200, max_depth = 3)
gb_13.fit(df_13_norm_train.iloc[:, 1:], df_13_norm_train.iloc[:, 0])
df_13_gb_predict = gb_13.predict(df_13_norm.iloc[:, 1:])
df_13_gb_predict

array([-0.44893065, -0.2333359 ,  0.02236934, -0.05283807, -0.1230316 ,
       -0.03779657,  0.05245231,  3.28135894,  0.24799176, -0.47399973,
       -0.27942111, -0.31543666, -0.31543666])

In [21]:
gb_13.feature_importances_

array([0.57645134, 0.40727567, 0.00761646, 0.00865653])

In [22]:
df_13_norm_gb = pd.DataFrame({'Russia_MoM_predict': df_13_gb_predict, 'MoM': df_13_norm.iloc[:, 1], 'YoY': df_13_norm.iloc[:, 2], 'Russia_MoM-1': df_13_norm.iloc[:, 3], 'Russia_YoY-1': df_13_norm.iloc[:, 4]})
df_13_norm_gb

Russia_MoM_predict       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0            -0.448931 -0.365105 -1.907280     -0.418912     -1.111940
1            -0.233336  0.224650 -1.760327     -0.490500     -1.060631
2             0.022369  1.233588 -1.029559     -0.270621     -0.892710
3            -0.052838  0.787670  0.022118     -0.009834     -0.722456
4            -0.123032  0.071492 -0.065008     -0.086536     -0.659486
5            -0.037797  0.523717  0.130469     -0.158124     -0.661818
6             0.052452 -0.281067  0.266272     -0.071195     -0.582522
7             3.281359  2.363568  1.723373      0.020847     -0.484568
8             0.247992 -1.351791  1.228319      3.313926      1.273941
9            -0.474000 -1.194510  0.584412      0.220273      1.539817
10           -0.279421 -0.938498  0.489096     -0.516068      1.369563
11           -0.315437 -0.631242  0.178621     -0.756401      1.089694
12           -0.315437 -0.442473  0.139493     -0.776855      0.903115

In [23]:
df_13_gb = pd.DataFrame(scaler.inverse_transform(df_13_norm_gb), columns=df_13_norm_gb.columns)
df_13_gb

Russia_MoM_predict         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0           100.170000   99.910265   99.651411        100.31        106.46
1           100.600000  101.387850  100.461306        100.17        106.68
2           101.110000  103.915668  104.488735        100.60        107.40
3           100.960000  102.798455  110.284777        101.11        108.13
4           100.820000  101.004126  109.804602        100.96        108.40
5           100.990000  102.137140  110.881921        100.82        108.39
6           101.170000  100.120816  111.630367        100.99        108.73
7           107.610000  106.746746  119.660790        101.17        109.15
8           101.560000   97.438199  116.932430        107.61        116.69
9           100.120000   97.832254  113.383708        101.56        117.83
10          100.508084   98.473673  112.858401        100.12        117.10
11          100.436251   99.243480  111.147299         99.65        115.90
12          100.436251   99.716424  110.931656         99.61        115.10

In [24]:
df_13_norm_train = df_13_norm.iloc[:-3]
df_13_norm_test = df_13_norm.iloc[-3:]
rf_13 = RandomForestRegressor(n_estimators = 100, max_depth = 9)
rf_13.fit(df_13_norm_train.iloc[:, 1:], df_13_norm_train.iloc[:, 0])
df_13_rf_predict = rf_13.predict(df_13_norm.iloc[:, 1:])
df_13_rf_predict

array([-0.31882174, -0.21523601, -0.05118349, -0.02481075, -0.08718279,
       -0.03288301, -0.00575819,  2.131788  ,  0.52535683, -0.25569762,
       -0.17823395, -0.16725366, -0.17111431])

In [25]:
rf_13.feature_importances_

array([0.42335617, 0.34350331, 0.10186745, 0.13127307])

In [26]:
df_13_norm_rf = pd.DataFrame({'Russia_MoM_predict': df_13_rf_predict, 'MoM': df_13_norm.iloc[:, 1], 'YoY': df_13_norm.iloc[:, 2], 'Russia_MoM-1': df_13_norm.iloc[:, 3], 'Russia_YoY-1': df_13_norm.iloc[:, 4]})
df_13_norm_rf

Russia_MoM_predict       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0            -0.318822 -0.365105 -1.907280     -0.418912     -1.111940
1            -0.215236  0.224650 -1.760327     -0.490500     -1.060631
2            -0.051183  1.233588 -1.029559     -0.270621     -0.892710
3            -0.024811  0.787670  0.022118     -0.009834     -0.722456
4            -0.087183  0.071492 -0.065008     -0.086536     -0.659486
5            -0.032883  0.523717  0.130469     -0.158124     -0.661818
6            -0.005758 -0.281067  0.266272     -0.071195     -0.582522
7             2.131788  2.363568  1.723373      0.020847     -0.484568
8             0.525357 -1.351791  1.228319      3.313926      1.273941
9            -0.255698 -1.194510  0.584412      0.220273      1.539817
10           -0.178234 -0.938498  0.489096     -0.516068      1.369563
11           -0.167254 -0.631242  0.178621     -0.756401      1.089694
12           -0.171114 -0.442473  0.139493     -0.776855      0.903115

In [27]:
df_13_rf = pd.DataFrame(scaler.inverse_transform(df_13_norm_rf), columns=df_13_norm_rf.columns)
df_13_rf

Russia_MoM_predict         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0             100.4295   99.910265   99.651411        100.31        106.46
1             100.6361  101.387850  100.461306        100.17        106.68
2             100.9633  103.915668  104.488735        100.60        107.40
3             101.0159  102.798455  110.284777        101.11        108.13
4             100.8915  101.004126  109.804602        100.96        108.40
5             100.9998  102.137140  110.881921        100.82        108.39
6             101.0539  100.120816  111.630367        100.99        108.73
7             105.3172  106.746746  119.660790        101.17        109.15
8             102.1132   97.438199  116.932430        107.61        116.69
9             100.5554   97.832254  113.383708        101.56        117.83
10            100.7099   98.473673  112.858401        100.12        117.10
11            100.7318   99.243480  111.147299         99.65        115.90
12            100.7241   99.716424  110.931656         99.61        115.10

In [28]:
fig1 = go.Figure()
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25_gb.iloc[:, 0], line_color="blue", name='Градиентный бустинг',)
)
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25_rf.iloc[:, 0], line_color="green", name='Случайный лес')
)
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25.iloc[:, 0], line_color="red", name='Фактические данные')
)
fig1.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>')

In [29]:
fig2 = go.Figure()
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_gb.iloc[:, 0], line_color="blue", name='Градиентный бустинг')
)
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_rf.iloc[:, 0], line_color="green", name='Случайный лес')
)
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_mom.iloc[:, 0], line_color="red", name='Фактические данные')
)
fig2.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>')

In [30]:
mean_absolute_error(df_25.iloc[-3:, 0], df_25_gb.iloc[-3:, 0])

0.6129807952979197

In [31]:
mean_absolute_error(df_25.iloc[-3:, 0], df_25_rf.iloc[-3:, 0])

0.661899999999998

In [32]:
mean_absolute_error(df_13_mom.iloc[-3:, 0], df_13_gb.iloc[-3:, 0])

0.8801956194783239

In [33]:
mean_absolute_error(df_13_mom.iloc[-3:, 0], df_13_rf.iloc[-3:, 0])

1.1419333333333366

In [34]:
fig3 = px.scatter(x=df_25.iloc[:, 0], y=df_25.iloc[:, 1])
fig3.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>', 
                   xaxis_title="Инфляция товаров из онлайн магазинов", 
                   yaxis_title="Инфляция на товары и услуги в России")
fig3.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

In [35]:
fig4 = px.scatter(x=df_25.iloc[:, 0], y=df_25.iloc[:, 2])
fig4.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>', 
                   xaxis_title="Инфляция на товары и услуги в России за прошлый месяц", 
                   yaxis_title="Инфляция на товары и услуги в России")
fig4.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

In [36]:
df_25_nn = df_25.copy()
df_25_nn['Spread'] = abs(df_25['MoM'] - df_25['Russia_MoM-1'])
df_25_nn

Russia_MoM         MoM  Russia_MoM-1     Spread
0        99.96   99.337024        100.35   1.012976
1        99.93  100.570486         99.96   0.610486
2       100.43   99.910327         99.93   0.019673
3       100.71   97.395858        100.43   3.034142
4       100.83  101.445817        100.71   0.735817
5       100.67  101.144785        100.83   0.314785
6       100.78   99.449539        100.67   1.220461
7       100.66   99.582982        100.78   1.197018
8       100.58   99.711704        100.66   0.948296
9       100.74  100.894241        100.58   0.314241
10      100.69   98.932025        100.74   1.807975
11      100.31  100.771324        100.69   0.081324
12      100.17   99.910265        100.31   0.399735
13      100.60  101.387850        100.17   1.217850
14      101.11  103.915668        100.60   3.315668
15      100.96  102.798455        101.11   1.688455
16      100.82  101.004126        100.96   0.044126
17      100.99  102.137140        100.82   1.317140
18      101.17  100.120816        100.99   0.869184
19      107.61  106.746746        101.17   5.576746
20      101.56   97.438199        107.61  10.171801
21      100.12   97.832254        101.56   3.727746
22       99.65   98.473673        100.12   1.646327
23       99.61   99.243480         99.65   0.406520
24       99.48   99.716424         99.61   0.106424

In [37]:
scaler_nn = preprocessing.StandardScaler()
names = df_25_nn.iloc[:,-1:].columns
df_25_nn_norm_spread = pd.DataFrame(scaler_nn.fit_transform(df_25_nn.iloc[:,-1:]), columns=names)
df_25_nn_norm_spread

Spread
0  -0.303152
1  -0.488467
2  -0.760491
3   0.627438
4  -0.430762
5  -0.624614
6  -0.207621
7  -0.218415
8  -0.332932
9  -0.624865
10  0.062884
11 -0.732105
12 -0.585502
13 -0.208823
14  0.757059
15  0.007854
16 -0.749232
17 -0.163107
18 -0.369357
19  1.798110
20  3.913776
21  0.946789
22 -0.011543
23 -0.582378
24 -0.720548

In [38]:
df_25_nn_norm = pd.concat([df_25_nn.iloc[:,:-1].reset_index(drop = True), df_25_nn_norm_spread.reset_index(drop = True)], axis=1)
df_25_nn_norm

Russia_MoM         MoM  Russia_MoM-1    Spread
0        99.96   99.337024        100.35 -0.303152
1        99.93  100.570486         99.96 -0.488467
2       100.43   99.910327         99.93 -0.760491
3       100.71   97.395858        100.43  0.627438
4       100.83  101.445817        100.71 -0.430762
5       100.67  101.144785        100.83 -0.624614
6       100.78   99.449539        100.67 -0.207621
7       100.66   99.582982        100.78 -0.218415
8       100.58   99.711704        100.66 -0.332932
9       100.74  100.894241        100.58 -0.624865
10      100.69   98.932025        100.74  0.062884
11      100.31  100.771324        100.69 -0.732105
12      100.17   99.910265        100.31 -0.585502
13      100.60  101.387850        100.17 -0.208823
14      101.11  103.915668        100.60  0.757059
15      100.96  102.798455        101.11  0.007854
16      100.82  101.004126        100.96 -0.749232
17      100.99  102.137140        100.82 -0.163107
18      101.17  100.120816        100.99 -0.369357
19      107.61  106.746746        101.17  1.798110
20      101.56   97.438199        107.61  3.913776
21      100.12   97.832254        101.56  0.946789
22       99.65   98.473673        100.12 -0.011543
23       99.61   99.243480         99.65 -0.582378
24       99.48   99.716424         99.61 -0.720548

In [142]:
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()
        self.l1 = nn.Linear(1, 2)
        self.tanh = nn.Tanh()
        self.l2 = nn.Linear(2, 2)
        self.tanh = nn.Tanh()
        self.l3 = nn.Linear(2, 1)
        self.sigm = nn.Sigmoid()
        
    def forward(self, x):
        #print(type(x))
        out = self.l1(x)
        #print(f"l1 {out}")
        out = self.tanh(out)
        #print(f"tanh {out}")
        out = self.l2(out)
        #print(f"l2 {out}")
        out = self.tanh(out)
        #print(f"tanh {out}")
        out = self.l3(out)
        #print(f"l3 {out}")
        out = self.sigm(out)
        #print(f"sigm {out}")
        return out

In [143]:
model = TheModelClass().to(torch.float64)
print(model)

TheModelClass(
  (l1): Linear(in_features=1, out_features=2, bias=True)
  (tanh): Tanh()
  (l2): Linear(in_features=2, out_features=2, bias=True)
  (l3): Linear(in_features=2, out_features=1, bias=True)
  (sigm): Sigmoid()
)


In [144]:
criterion = nn.L1Loss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)

In [145]:
for i in iter(model.parameters()):
    print(i)

Parameter containing:
tensor([[ 0.5512],
        [-0.6164]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([ 0.9438, -0.2280], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.3784, -0.2202],
        [ 0.6698, -0.1817]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([ 0.3175, -0.0635], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.4225, 0.3422]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0962], dtype=torch.float64, requires_grad=True)


In [146]:
train_dataset = torch.tensor(df_25_nn_norm.iloc[:-3, :].reset_index(drop = True).to_numpy())
train_dataset

tensor([[ 9.9960e+01,  9.9337e+01,  1.0035e+02, -3.0315e-01],
        [ 9.9930e+01,  1.0057e+02,  9.9960e+01, -4.8847e-01],
        [ 1.0043e+02,  9.9910e+01,  9.9930e+01, -7.6049e-01],
        [ 1.0071e+02,  9.7396e+01,  1.0043e+02,  6.2744e-01],
        [ 1.0083e+02,  1.0145e+02,  1.0071e+02, -4.3076e-01],
        [ 1.0067e+02,  1.0114e+02,  1.0083e+02, -6.2461e-01],
        [ 1.0078e+02,  9.9450e+01,  1.0067e+02, -2.0762e-01],
        [ 1.0066e+02,  9.9583e+01,  1.0078e+02, -2.1841e-01],
        [ 1.0058e+02,  9.9712e+01,  1.0066e+02, -3.3293e-01],
        [ 1.0074e+02,  1.0089e+02,  1.0058e+02, -6.2486e-01],
        [ 1.0069e+02,  9.8932e+01,  1.0074e+02,  6.2884e-02],
        [ 1.0031e+02,  1.0077e+02,  1.0069e+02, -7.3210e-01],
        [ 1.0017e+02,  9.9910e+01,  1.0031e+02, -5.8550e-01],
        [ 1.0060e+02,  1.0139e+02,  1.0017e+02, -2.0882e-01],
        [ 1.0111e+02,  1.0392e+02,  1.0060e+02,  7.5706e-01],
        [ 1.0096e+02,  1.0280e+02,  1.0111e+02,  7.8541e-03],
        

In [147]:
test_dataset = torch.tensor(df_25_nn_norm.iloc[-3:, :].reset_index(drop = True).to_numpy())
test_dataset

tensor([[ 9.9650e+01,  9.8474e+01,  1.0012e+02, -1.1543e-02],
        [ 9.9610e+01,  9.9243e+01,  9.9650e+01, -5.8238e-01],
        [ 9.9480e+01,  9.9716e+01,  9.9610e+01, -7.2055e-01]],
       dtype=torch.float64)

In [148]:
# train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
#                                            batch_size=len(train_dataset), 
#                                            shuffle=False)
# test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
#                                           batch_size=len(test_dataset),
#                                           shuffle=False)

In [149]:
optimizer.param_groups[0]['lr']

0.1

In [150]:
with torch.no_grad():
    num_epochs = 1000000
    optimizer.param_groups[0]['lr'] = 0.1
    best_model = copy.deepcopy(model)
    best_outputs_test = (best_model(torch.unsqueeze(test_dataset[:,-1], 1))*torch.unsqueeze(test_dataset[:,-2], 1)) \
                        + ((1-best_model(torch.unsqueeze(test_dataset[:,-1], 1)))*torch.unsqueeze(test_dataset[:,-3], 1))
    best_loss_test = criterion(best_outputs_test, torch.unsqueeze(test_dataset[:,0], 1))
    i = 0
for epoch in range(num_epochs):
    outputs_train = (model(torch.unsqueeze(train_dataset[:,-1], 1))*torch.unsqueeze(train_dataset[:,-2], 1)) \
                        + ((1-model(torch.unsqueeze(train_dataset[:,-1], 1)))*torch.unsqueeze(train_dataset[:,-3], 1))
    loss_train = criterion(outputs_train, torch.unsqueeze(train_dataset[:,0], 1))

    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()
    
    with torch.no_grad():
        outputs_test = (model(torch.unsqueeze(test_dataset[:,-1], 1))*torch.unsqueeze(test_dataset[:,-2], 1)) \
                        + ((1-model(torch.unsqueeze(test_dataset[:,-1], 1)))*torch.unsqueeze(test_dataset[:,-3], 1))
        loss_test = criterion(outputs_test, torch.unsqueeze(test_dataset[:,0], 1))
        
        best_outputs_test = (best_model(torch.unsqueeze(test_dataset[:,-1], 1))*torch.unsqueeze(test_dataset[:,-2], 1)) \
                        + ((1-best_model(torch.unsqueeze(test_dataset[:,-1], 1)))*torch.unsqueeze(test_dataset[:,-3], 1))
        best_loss_test = criterion(best_outputs_test, torch.unsqueeze(test_dataset[:,0], 1))
    
        if epoch == 0:
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_test:.4}], Test-Loss: [{loss_train:.4}]')
            
        if loss_test < best_loss_test - 1e-9:   
            best_model = copy.deepcopy(model)
            best_loss_test = loss_test
            i = 0
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_train:.4}], Test-Loss: [{loss_test:.4}]')
        else:
            i += 1

        if i == 3000 and optimizer.param_groups[0]['lr'] / 2 > 1e-9:
            
            optimizer.param_groups[0]['lr'] = optimizer.param_groups[0]['lr'] / 2
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_train:.4}]')
            i = 0
        elif optimizer.param_groups[0]['lr'] / 2 < 1e-9:
            learning_rate = optimizer.param_groups[0]['lr']
            print(f"На {epoch+1} эпохе Learning Rate стал слишком мал - {learning_rate:.4}") 
            break
            
        if num_epochs == 100000 - 1:
            print("Все эпохи прошли")            
        
for parameter in best_model.named_parameters():
    print(parameter)

Epoch [1], Learning Rate: [0.1], Train-Loss: [0.2174], Test-Loss: [0.6828]
Epoch [1], Learning Rate: [0.1], Train-Loss: [0.6828], Test-Loss: [0.2174]
Epoch [2], Learning Rate: [0.1], Train-Loss: [0.6816], Test-Loss: [0.2133]
Epoch [3], Learning Rate: [0.1], Train-Loss: [0.6792], Test-Loss: [0.2073]
Epoch [4], Learning Rate: [0.1], Train-Loss: [0.6758], Test-Loss: [0.1997]
Epoch [5], Learning Rate: [0.1], Train-Loss: [0.6715], Test-Loss: [0.1908]
Epoch [6], Learning Rate: [0.1], Train-Loss: [0.6665], Test-Loss: [0.1806]
Epoch [7], Learning Rate: [0.1], Train-Loss: [0.6608], Test-Loss: [0.1693]
Epoch [8], Learning Rate: [0.1], Train-Loss: [0.6546], Test-Loss: [0.1572]
Epoch [9], Learning Rate: [0.1], Train-Loss: [0.6494], Test-Loss: [0.1466]
Epoch [10], Learning Rate: [0.1], Train-Loss: [0.648], Test-Loss: [0.1382]
Epoch [11], Learning Rate: [0.1], Train-Loss: [0.6473], Test-Loss: [0.1317]
Epoch [12], Learning Rate: [0.1], Train-Loss: [0.6461], Test-Loss: [0.1269]
Epoch [13], Learning Ra

In [151]:
outputs_train_model = (model(torch.unsqueeze(train_dataset[:,-1], 1))*torch.unsqueeze(train_dataset[:,-2], 1)) \
                        + ((1-model(torch.unsqueeze(train_dataset[:,-1], 1)))*torch.unsqueeze(train_dataset[:,-3], 1))
outputs_train_model

tensor([[100.2272],
        [100.0563],
        [ 99.9263],
        [100.4259],
        [100.8187],
        [100.8856],
        [100.5511],
        [100.6600],
        [100.5386],
        [100.6355],
        [100.6900],
        [100.7053],
        [100.2413],
        [100.2890],
        [101.1100],
        [101.1771],
        [100.9684],
        [100.9325],
        [100.8720],
        [106.7449],
        [101.5600],
        [100.1200]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [152]:
model(torch.unsqueeze(train_dataset[:,-1], 1))

tensor([[8.7875e-01],
        [8.4231e-01],
        [8.0941e-01],
        [9.9865e-01],
        [8.5224e-01],
        [8.2333e-01],
        [9.0259e-01],
        [8.9975e-01],
        [8.7199e-01],
        [8.2330e-01],
        [9.7234e-01],
        [8.1197e-01],
        [8.2820e-01],
        [9.0227e-01],
        [8.4618e-01],
        [9.6023e-01],
        [8.1041e-01],
        [9.1459e-01],
        [8.6420e-01],
        [3.2557e-04],
        [4.0522e-01],
        [6.1371e-01]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [153]:
outputs_test_model = (model(torch.unsqueeze(test_dataset[:,-1], 1))*torch.unsqueeze(test_dataset[:,-2], 1)) \
                        + ((1-model(torch.unsqueeze(test_dataset[:,-1], 1)))*torch.unsqueeze(test_dataset[:,-3], 1))
outputs_test_model

tensor([[100.0467],
        [ 99.5803],
        [ 99.6299]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [154]:
model(torch.unsqueeze(test_dataset[:,-1], 1))

tensor([[0.9555],
        [0.8286],
        [0.8131]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [155]:
outputs_train_best_model = (best_model(torch.unsqueeze(train_dataset[:,-1], 1))*torch.unsqueeze(train_dataset[:,-2], 1)) \
                        + ((1-best_model(torch.unsqueeze(train_dataset[:,-1], 1)))*torch.unsqueeze(train_dataset[:,-3], 1))
outputs_train_best_model

tensor([[100.1018],
        [100.0984],
        [ 99.9259],
        [ 99.3219],
        [100.8807],
        [100.8978],
        [100.3579],
        [100.4754],
        [100.4307],
        [100.6477],
        [100.2160],
        [100.7069],
        [100.2227],
        [100.4812],
        [101.8617],
        [101.5870],
        [100.9691],
        [101.1637],
        [100.7831],
        [103.7139],
        [102.6617],
        [100.0671]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [156]:
outputs_test_best_model = (best_model(torch.unsqueeze(test_dataset[:,-1], 1))*torch.unsqueeze(test_dataset[:,-2], 1)) \
                        + ((1-best_model(torch.unsqueeze(test_dataset[:,-1], 1)))*torch.unsqueeze(test_dataset[:,-3], 1))
outputs_test_best_model

tensor([[99.6590],
        [99.5611],
        [99.6322]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [209]:
criterion(outputs_train_model, torch.unsqueeze(train_dataset[:,0], 1))

tensor(0.1885, dtype=torch.float64, grad_fn=<L1LossBackward0>)

In [210]:
criterion(outputs_test_model, torch.unsqueeze(test_dataset[:,0], 1))

tensor(0.1921, dtype=torch.float64, grad_fn=<L1LossBackward0>)

In [159]:
criterion(outputs_train_best_model, torch.unsqueeze(train_dataset[:,0], 1))

tensor(0.5232, dtype=torch.float64, grad_fn=<L1LossBackward0>)

In [160]:
criterion(outputs_test_best_model, torch.unsqueeze(test_dataset[:,0], 1))

tensor(0.0701, dtype=torch.float64, grad_fn=<L1LossBackward0>)

In [165]:
# torch.save(model, "NN_Spread_1_2_Tanh_2_2_Tanh_2_1_Sigmoid.pth")

In [208]:
model = torch.load('NN_Spread_1_2_Tanh_2_2_Tanh_2_1_Sigmoid.pth')

In [167]:
for parameter in best_model.named_parameters():
    print(parameter)

('l1.weight', Parameter containing:
tensor([[ 0.5531],
        [-0.6037]], dtype=torch.float64, requires_grad=True))
('l1.bias', Parameter containing:
tensor([ 0.8388, -0.0889], dtype=torch.float64, requires_grad=True))
('l2.weight', Parameter containing:
tensor([[-0.5437,  0.8576],
        [ 0.7904,  0.1010]], dtype=torch.float64, requires_grad=True))
('l2.bias', Parameter containing:
tensor([0.7206, 0.3016], dtype=torch.float64, requires_grad=True))
('l3.weight', Parameter containing:
tensor([[1.0515, 0.1107]], dtype=torch.float64, requires_grad=True))
('l3.bias', Parameter containing:
tensor([0.5822], dtype=torch.float64, requires_grad=True))


In [193]:
outputs_train_model

tensor([[100.2272],
        [100.0563],
        [ 99.9263],
        [100.4259],
        [100.8187],
        [100.8856],
        [100.5511],
        [100.6600],
        [100.5386],
        [100.6355],
        [100.6900],
        [100.7053],
        [100.2413],
        [100.2890],
        [101.1100],
        [101.1771],
        [100.9684],
        [100.9325],
        [100.8720],
        [106.7449],
        [101.5600],
        [100.1200]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [194]:
tens = torch.cat((outputs_train_model, outputs_test_model), 0)
tens

tensor([[100.2272],
        [100.0563],
        [ 99.9263],
        [100.4259],
        [100.8187],
        [100.8856],
        [100.5511],
        [100.6600],
        [100.5386],
        [100.6355],
        [100.6900],
        [100.7053],
        [100.2413],
        [100.2890],
        [101.1100],
        [101.1771],
        [100.9684],
        [100.9325],
        [100.8720],
        [106.7449],
        [101.5600],
        [100.1200],
        [100.0467],
        [ 99.5803],
        [ 99.6299]], dtype=torch.float64, grad_fn=<CatBackward0>)

In [206]:
df_25_nn_norm_prediction = pd.DataFrame(tens.detach().numpy())
df_25_nn_norm_prediction.columns = ['Russia_MoM_predict']
df_25_nn_norm_prediction

Russia_MoM_predict
0           100.227175
1           100.056265
2            99.926251
3           100.425917
4           100.818722
5           100.885613
6           100.551115
7           100.660000
8           100.538608
9           100.635526
10          100.690000
11          100.705291
12          100.241327
13          100.289017
14          101.110000
15          101.177147
16          100.968366
17          100.932502
18          100.871962
19          106.744930
20          101.560000
21          100.120000
22          100.046731
23           99.580327
24           99.629894

In [207]:
fig5 = go.Figure()
fig5.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25_nn_norm_prediction.iloc[:, 0], line_color="blue", name='Нейронная сеть',)
)
fig5.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25.iloc[:, 0], line_color="red", name='Фактические данные')
)
fig5.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>')