<a href="https://www.kaggle.com/code/aleksandr13254/mysolve?scriptVersionId=109305255" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from tqdm import tqdm # loops show a smart progress meter
from sklearn import preprocessing
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
import torch
import torch.nn as nn
import copy
import plotly.graph_objects as go
import plotly.express as px

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/dataset/DS_tests/DS_test9(2020-06--2022-09-01).csv
/kaggle/input/dataset/DS_tests/DS_test8(2020-06--2022-08-21).csv
/kaggle/input/dataset/DS_tests/DS_test5(2020-06--2022-07-21).csv
/kaggle/input/dataset/DS_tests/DS_test4(2020-06--2022-07-11).csv
/kaggle/input/dataset/DS_tests/DS_test7(2020-06--2022-08-11).csv
/kaggle/input/dataset/DS_tests/DS_test1(2020-06--2022-06-11).csv
/kaggle/input/dataset/DS_tests/DS_test3(2020-06--2022-07-01).csv
/kaggle/input/dataset/DS_tests/DS_test6(2020-06--2022-08-01).csv
/kaggle/input/dataset/DS_tests/DS_test2(2020-06--2022-06-21).csv
/kaggle/input/dataset/DS_train/DS_train(2020-06--2022-06-01).csv
/kaggle/input/dataset-cpi-test/CPI_MoM.csv
/kaggle/input/dataset-cpi-test/CPI_YoY.csv
/kaggle/input/dataset-cpi-test/CPI_Russia.csv
/kaggle/input/dataset-cpi-test/Product_Price_Month.csv
/kaggle/input/dataset-cpi-test/Product_Price_Day.csv
/kaggle/input/dataset-cpi-test/Product_CPI.csv


In [ ]:
df = pd.read_csv('../input/dataset/DS_tests/DS_test9(2020-06--2022-09-01).csv', delimiter='\t',parse_dates=['DateObserve'])
# df = pd.read_csv('../input/dataset/DS_train/DS_train(2020-06--2022-06-01).csv', delimiter='\t',parse_dates=['DateObserve'], nrows=107892)
df

In [ ]:
df = df[df['StockStatus']=='InStock'][['WebPriceId','DateObserve','CurrentPrice']]
df

In [ ]:
df.dropna()
df

In [ ]:
df['DateObserve'] = pd.to_datetime(df['DateObserve']).apply(lambda x: x.strftime('%Y-%m-%d'))
df

In [ ]:
df = df.groupby(['WebPriceId','DateObserve']).agg({'CurrentPrice': ['mean']}).reset_index()
df.columns = ['Id','Date','Price']
df

In [ ]:
df = df[df['Price'] < 100000]
df

In [ ]:
df = df[df['Price'] > 10]
df

In [ ]:
count_filtered = df.groupby(['Id'])['Id'].count()
count_filtered

In [ ]:
filtered_ids = pd.DataFrame(count_filtered[count_filtered > 60].index)
filtered_ids

In [ ]:
df = filtered_ids.merge(df, on='Id',how='inner')
df

In [ ]:
df.to_csv('Product_Price_Day.csv',sep=';',encoding='utf-8')
# df = pd.read_csv('../input/dataset-cpi-test/Product_Price_Day.csv', delimiter=';', index_col=[0])
df

In [ ]:
df['Date'] = pd.to_datetime(df['Date']).apply(lambda x: x.strftime('%Y-%m'))
df

In [ ]:
df = df.groupby(['Id','Date']).agg({'Price': ['mean']}).reset_index()
df.columns = ['Id','Date','Price']
df

In [ ]:
df.to_csv('Product_Price_Month.csv',sep=';',encoding='utf-8')
# df = pd.read_csv('../input/dataset-cpi-test/Product_Price_Month.csv', delimiter=';', index_col=[0])
df

In [ ]:
date_list_all = df.sort_values(by=['Date']).Date.unique()
date_list_all

In [ ]:
id_product_list = df['Id'].unique()[:-1]
len(id_product_list)

In [ ]:
id_list = list()
date_start_list = list()
date_end_list = list()
cpi_product_list = list()
for id_product in tqdm(id_product_list):
    df_id_product = df.loc[df.Id == id_product]
    date_list = df_id_product.sort_values(by=['Date']).Date.unique()
    for i in range(0, len(date_list)):        
        start_value = df_id_product.loc[df_id_product.Date == date_list[i]].Price.values[0]
        for j in range(i+1, len(date_list)):
            end_value = df_id_product.loc[df_id_product.Date == date_list[j]].Price.values[0]
            cpi_product = end_value/start_value*100
            id_list.append(id_product)
            date_start_list.append(date_list[i])
            date_end_list.append(date_list[j])
            cpi_product_list.append(cpi_product)

In [ ]:
cpi_id_product = pd.DataFrame({'Id': id_list, 'Date_start': date_start_list, 'Date_end': date_end_list, 'CPI': cpi_product_list})
cpi_id_product

In [ ]:
cpi_id_product.to_csv('Product_CPI.csv',sep=';',encoding='utf-8')
# cpi_id_product = pd.read_csv('../input/dataset-cpi-test/Product_CPI.csv', delimiter=';', index_col=[0])
cpi_id_product

In [ ]:
cpi_id_product = cpi_id_product[cpi_id_product.CPI < 120][cpi_id_product.CPI > 80]
cpi_id_product

In [ ]:
cpi_count = cpi_id_product[['Id','Date_start','Date_end',]].groupby(['Date_end','Date_start']).count().reset_index()
cpi_count.columns = ['Date_end','Date_start','Count_Id',]
cpi_count

In [ ]:
date_list_year = ['2020', '2021', '2022']
date_list_month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
date_list_year_month = list()
cpi_list = list()
cpi_date_list = list()
for y in date_list_year:
    for m in date_list_month:
        date_list_year_month.append(f'{y}-{m}')
for i in range(1, len(date_list_year_month)):
    item = cpi_count.loc[(cpi_count.Date_start == date_list_year_month[i-1]) & (cpi_count.Date_end == date_list_year_month[i])]
    if item.empty == False:
        cpi_list.append(item.Count_Id.values[0])
        cpi_date_list.append(item.Date_end.values[0])
cpi_id_count = pd.DataFrame({'Date': cpi_date_list, 'Count_Id': cpi_list})
cpi_id_count

In [ ]:
cpi_df = cpi_id_product.groupby(['Date_start','Date_end']).agg({'CPI': ['mean']}).reset_index()
cpi_df.columns = ['Date_start','Date_end','CPI']
cpi_df

In [ ]:
date_list_year = ['2020', '2021', '2022']
date_list_month = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
date_list_year_month = list()
cpi_list = list()
cpi_date_list = list()
for y in date_list_year:
    for m in date_list_month:
        date_list_year_month.append(f'{y}-{m}')
for i in range(1, len(date_list_year_month)):
    item = cpi_df.loc[(cpi_df.Date_start == date_list_year_month[i-1]) & (cpi_df.Date_end == date_list_year_month[i])]
    if item.empty == False:
        cpi_list.append(item.CPI.values[0])
        cpi_date_list.append(item.Date_end.values[0])
cpi_mom = pd.DataFrame({'Date': cpi_date_list, 'MoM': cpi_list})
cpi_mom

In [ ]:
cpi_yoy = cpi_mom.copy()
for i in range(12, len(cpi_yoy)):
  temp = 100
  for j in range(11, -1, -1):
    temp *= float(cpi_mom.iloc[i-j, 1])/100
  cpi_yoy.iloc[i, 1] = temp
cpi_yoy = cpi_yoy.iloc[12:, :].reset_index(drop = True)
cpi_yoy.columns = ['Date','YoY']
cpi_yoy

In [9]:
# cpi_mom.to_csv('CPI_MoM.csv',sep=';',encoding='utf-8')
cpi_mom = pd.read_csv('../input/dataset-cpi-test/CPI_MoM.csv', delimiter=';', index_col=[0])
cpi_mom

Date         MoM
0   2020-07   99.851962
1   2020-08   99.337024
2   2020-09  100.570486
3   2020-10   99.910327
4   2020-11   97.395858
5   2020-12  101.445817
6   2021-01  101.144785
7   2021-02   99.449539
8   2021-03   99.582982
9   2021-04   99.711704
10  2021-05  100.894241
11  2021-06   98.932025
12  2021-07  100.771324
13  2021-08   99.910265
14  2021-09  101.387850
15  2021-10  103.915668
16  2021-11  102.798455
17  2021-12  101.004126
18  2022-01  102.137140
19  2022-02  100.120816
20  2022-03  106.746746
21  2022-04   97.438199
22  2022-05   97.832254
23  2022-06   98.473673
24  2022-07   99.243480
25  2022-08   99.716424

In [10]:
# cpi_yoy.to_csv('CPI_YoY.csv',sep=';',encoding='utf-8')
cpi_yoy = pd.read_csv('../input/dataset-cpi-test/CPI_YoY.csv', delimiter=';', index_col=[0])
cpi_yoy = cpi_yoy.iloc[:,1:].reset_index(drop = True)
cpi_yoy

YoY
0    99.079655
1    99.651411
2   100.461306
3   104.488735
4   110.284777
5   109.804602
6   110.881921
7   111.630367
8   119.660790
9   116.932430
10  113.383708
11  112.858401
12  111.147299
13  110.931656

In [11]:
cpi_russia = pd.read_csv('../input/dataset-cpi-test/CPI_Russia.csv', delimiter=';')
cpi_russia = cpi_russia
cpi_russia

Date  Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY
0   2020-07      100.35      103.37   100.36   103.25  100.48  103.92
1   2020-08       99.96      103.58    99.87   103.42  100.02  104.48
2   2020-09       99.93      103.67    99.89   103.48   99.86  104.44
3   2020-10      100.43      103.99   100.38   103.78  100.56  105.06
4   2020-11      100.71      104.42   100.65   104.16  100.73  105.43
5   2020-12      100.83      104.91   100.84   104.70  100.82  105.79
6   2021-01      100.67      105.19   100.79   105.11  101.00  106.34
7   2021-02      100.78      105.67   100.71   105.55  101.03  106.99
8   2021-03      100.66      105.79   100.63   105.71  100.58  106.64
9   2021-04      100.58      105.53   100.54   105.54  100.78  106.53
10  2021-05      100.74      106.02   100.82   105.97  100.88  107.20
11  2021-06      100.69      106.50   100.74   106.40  100.77  107.76
12  2021-07      100.31      106.46   100.26   106.30  100.31  107.57
13  2021-08      100.17      106.68   100.10   106.53  100.29  107.87
14  2021-09      100.60      107.40   100.66   107.35  100.53  108.60
15  2021-10      101.11      108.13   101.02   108.03  101.51  109.63
16  2021-11      100.96      108.40   100.96   108.36  100.86  109.77
17  2021-12      100.82      108.39   100.80   108.32  100.97  109.94
18  2022-01      100.99      108.73   100.96   108.50  101.22  110.18
19  2022-02      101.17      109.15   101.42   109.26  101.13  110.28
20  2022-03      107.61      116.69   107.37   116.58  109.02  119.54
21  2022-04      101.56      117.83   101.74   117.97  102.40  121.46
22  2022-05      100.12      117.10   100.23   117.29  100.01  120.41
23  2022-06       99.65      115.90    99.91   116.32   99.73  119.17
24  2022-07       99.61      115.10    99.57   115.52   99.34  118.02
25  2022-08       99.48      114.30    99.55   114.89   99.24  116.78

In [12]:
df_14 = pd.concat([cpi_russia.iloc[12:,1:].reset_index(drop = True), cpi_mom.iloc[12:,1:].reset_index(drop = True), cpi_yoy], axis=1)
df_14

Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY         MoM  \
0       100.31      106.46   100.26   106.30  100.31  107.57  100.771324   
1       100.17      106.68   100.10   106.53  100.29  107.87   99.910265   
2       100.60      107.40   100.66   107.35  100.53  108.60  101.387850   
3       101.11      108.13   101.02   108.03  101.51  109.63  103.915668   
4       100.96      108.40   100.96   108.36  100.86  109.77  102.798455   
5       100.82      108.39   100.80   108.32  100.97  109.94  101.004126   
6       100.99      108.73   100.96   108.50  101.22  110.18  102.137140   
7       101.17      109.15   101.42   109.26  101.13  110.28  100.120816   
8       107.61      116.69   107.37   116.58  109.02  119.54  106.746746   
9       101.56      117.83   101.74   117.97  102.40  121.46   97.438199   
10      100.12      117.10   100.23   117.29  100.01  120.41   97.832254   
11       99.65      115.90    99.91   116.32   99.73  119.17   98.473673   
12       99.61      115.10    99.57   115.52   99.34  118.02   99.243480   
13       99.48      114.30    99.55   114.89   99.24  116.78   99.716424   

           YoY  
0    99.079655  
1    99.651411  
2   100.461306  
3   104.488735  
4   110.284777  
5   109.804602  
6   110.881921  
7   111.630367  
8   119.660790  
9   116.932430  
10  113.383708  
11  112.858401  
12  111.147299  
13  110.931656

In [13]:
df_13_mom = df_14.iloc[:,[0,-2,-1]].copy()
df_13_mom['Russia_MoM-1'] = df_14['Russia_MoM'].shift(1)
df_13_mom['Russia_YoY-1'] = df_14['Russia_YoY'].shift(1)
df_13_mom = df_13_mom.iloc[1:,:].reset_index(drop = True)
df_13_mom

Russia_MoM         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0       100.17   99.910265   99.651411        100.31        106.46
1       100.60  101.387850  100.461306        100.17        106.68
2       101.11  103.915668  104.488735        100.60        107.40
3       100.96  102.798455  110.284777        101.11        108.13
4       100.82  101.004126  109.804602        100.96        108.40
5       100.99  102.137140  110.881921        100.82        108.39
6       101.17  100.120816  111.630367        100.99        108.73
7       107.61  106.746746  119.660790        101.17        109.15
8       101.56   97.438199  116.932430        107.61        116.69
9       100.12   97.832254  113.383708        101.56        117.83
10       99.65   98.473673  112.858401        100.12        117.10
11       99.61   99.243480  111.147299         99.65        115.90
12       99.48   99.716424  110.931656         99.61        115.10

In [14]:
df_13_yoy = df_14.iloc[:,[1,-2,-1]].copy()
df_13_yoy['Russia_MoM-1'] = df_14['Russia_MoM'].shift(1)
df_13_yoy['Russia_YoY-1'] = df_14['Russia_YoY'].shift(1)
df_13_yoy = df_13_yoy.iloc[1:,:].reset_index(drop = True)
df_13_yoy

Russia_YoY         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0       106.68   99.910265   99.651411        100.31        106.46
1       107.40  101.387850  100.461306        100.17        106.68
2       108.13  103.915668  104.488735        100.60        107.40
3       108.40  102.798455  110.284777        101.11        108.13
4       108.39  101.004126  109.804602        100.96        108.40
5       108.73  102.137140  110.881921        100.82        108.39
6       109.15  100.120816  111.630367        100.99        108.73
7       116.69  106.746746  119.660790        101.17        109.15
8       117.83   97.438199  116.932430        107.61        116.69
9       117.10   97.832254  113.383708        101.56        117.83
10      115.90   98.473673  112.858401        100.12        117.10
11      115.10   99.243480  111.147299         99.65        115.90
12      114.30   99.716424  110.931656         99.61        115.10

In [15]:
df_26 = pd.concat([cpi_russia.iloc[:,1:], cpi_mom.iloc[:,1:]], axis=1)
df_26

Russia_MoM  Russia_YoY  CFD_MoM  CFD_YoY  Iv_MoM  Iv_YoY         MoM
0       100.35      103.37   100.36   103.25  100.48  103.92   99.851962
1        99.96      103.58    99.87   103.42  100.02  104.48   99.337024
2        99.93      103.67    99.89   103.48   99.86  104.44  100.570486
3       100.43      103.99   100.38   103.78  100.56  105.06   99.910327
4       100.71      104.42   100.65   104.16  100.73  105.43   97.395858
5       100.83      104.91   100.84   104.70  100.82  105.79  101.445817
6       100.67      105.19   100.79   105.11  101.00  106.34  101.144785
7       100.78      105.67   100.71   105.55  101.03  106.99   99.449539
8       100.66      105.79   100.63   105.71  100.58  106.64   99.582982
9       100.58      105.53   100.54   105.54  100.78  106.53   99.711704
10      100.74      106.02   100.82   105.97  100.88  107.20  100.894241
11      100.69      106.50   100.74   106.40  100.77  107.76   98.932025
12      100.31      106.46   100.26   106.30  100.31  107.57  100.771324
13      100.17      106.68   100.10   106.53  100.29  107.87   99.910265
14      100.60      107.40   100.66   107.35  100.53  108.60  101.387850
15      101.11      108.13   101.02   108.03  101.51  109.63  103.915668
16      100.96      108.40   100.96   108.36  100.86  109.77  102.798455
17      100.82      108.39   100.80   108.32  100.97  109.94  101.004126
18      100.99      108.73   100.96   108.50  101.22  110.18  102.137140
19      101.17      109.15   101.42   109.26  101.13  110.28  100.120816
20      107.61      116.69   107.37   116.58  109.02  119.54  106.746746
21      101.56      117.83   101.74   117.97  102.40  121.46   97.438199
22      100.12      117.10   100.23   117.29  100.01  120.41   97.832254
23       99.65      115.90    99.91   116.32   99.73  119.17   98.473673
24       99.61      115.10    99.57   115.52   99.34  118.02   99.243480
25       99.48      114.30    99.55   114.89   99.24  116.78   99.716424

In [16]:
df_25 = df_26.iloc[:,[0,-1]].copy()
df_25['Russia_MoM-1'] = df_26['Russia_MoM'].shift(1)
df_25 = df_25.iloc[1:,:].reset_index(drop = True)
df_25

Russia_MoM         MoM  Russia_MoM-1
0        99.96   99.337024        100.35
1        99.93  100.570486         99.96
2       100.43   99.910327         99.93
3       100.71   97.395858        100.43
4       100.83  101.445817        100.71
5       100.67  101.144785        100.83
6       100.78   99.449539        100.67
7       100.66   99.582982        100.78
8       100.58   99.711704        100.66
9       100.74  100.894241        100.58
10      100.69   98.932025        100.74
11      100.31  100.771324        100.69
12      100.17   99.910265        100.31
13      100.60  101.387850        100.17
14      101.11  103.915668        100.60
15      100.96  102.798455        101.11
16      100.82  101.004126        100.96
17      100.99  102.137140        100.82
18      101.17  100.120816        100.99
19      107.61  106.746746        101.17
20      101.56   97.438199        107.61
21      100.12   97.832254        101.56
22       99.65   98.473673        100.12
23       99.61   99.243480         99.65
24       99.48   99.716424         99.61

In [17]:
scaler = preprocessing.StandardScaler()
names = df_25.columns
df_25_norm = pd.DataFrame(scaler.fit_transform(df_25), columns=names)
df_25_norm

Russia_MoM       MoM  Russia_MoM-1
0    -0.572304 -0.527321     -0.336815
1    -0.592608  0.087555     -0.604673
2    -0.254207 -0.241532     -0.625278
3    -0.064702 -1.494985     -0.281869
4     0.016514  0.523904     -0.089561
5    -0.091774  0.373840     -0.007143
6    -0.017326 -0.471233     -0.117034
7    -0.098542 -0.404712     -0.041484
8    -0.152687 -0.340545     -0.123902
9    -0.044398  0.248945     -0.178847
10   -0.078238 -0.729212     -0.068956
11   -0.335423  0.187672     -0.103297
12   -0.430176 -0.241563     -0.364287
13   -0.139151  0.495008     -0.460442
14    0.206019  1.755115     -0.165111
15    0.104498  1.198189      0.185166
16    0.009746  0.303723      0.082143
17    0.124802  0.868526     -0.014011
18    0.246627 -0.136604      0.102748
19    4.605235  3.166397      0.226375
20    0.510580 -1.473878      4.649473
21   -0.464016 -1.277444      0.494233
22   -0.782113 -0.957699     -0.494783
23   -0.809185 -0.573953     -0.817586
24   -0.897169 -0.338192     -0.845059

In [18]:
df_25_norm_train = df_25_norm.iloc[:-3]
df_25_norm_test = df_25_norm.iloc[-3:]
gb_25 = GradientBoostingRegressor(n_estimators = 200, max_depth = 3)
gb_25.fit(df_25_norm_train.iloc[:, 1:], df_25_norm_train.iloc[:, 0])
df_25_gb_predict = gb_25.predict(df_25_norm.iloc[:, 1:])
df_25_gb_predict

array([-0.57165984, -0.59216484, -0.25425537, -0.06493963,  0.01671039,
       -0.09092903, -0.01830373, -0.0978253 , -0.15202693, -0.04509012,
       -0.07874059, -0.3349132 , -0.43046644, -0.13929548,  0.20611315,
        0.10489401,  0.00947239,  0.12396665,  0.24596516,  4.6048977 ,
        0.51050351, -0.46344519, -0.53654844, -0.43048329, -0.32921356])

In [19]:
gb_25.feature_importances_

array([0.95119668, 0.04880332])

In [20]:
df_25_norm_gb = pd.DataFrame({'Russia_MoM_predict': df_25_gb_predict, 'MoM': df_25_norm.iloc[:, 1], 'Russia_MoM-1': df_25_norm.iloc[:, 2]})
df_25_norm_gb

Russia_MoM_predict       MoM  Russia_MoM-1
0            -0.571660 -0.527321     -0.336815
1            -0.592165  0.087555     -0.604673
2            -0.254255 -0.241532     -0.625278
3            -0.064940 -1.494985     -0.281869
4             0.016710  0.523904     -0.089561
5            -0.090929  0.373840     -0.007143
6            -0.018304 -0.471233     -0.117034
7            -0.097825 -0.404712     -0.041484
8            -0.152027 -0.340545     -0.123902
9            -0.045090  0.248945     -0.178847
10           -0.078741 -0.729212     -0.068956
11           -0.334913  0.187672     -0.103297
12           -0.430466 -0.241563     -0.364287
13           -0.139295  0.495008     -0.460442
14            0.206113  1.755115     -0.165111
15            0.104894  1.198189      0.185166
16            0.009472  0.303723      0.082143
17            0.123967  0.868526     -0.014011
18            0.245965 -0.136604      0.102748
19            4.604898  3.166397      0.226375
20            0.510504 -1.473878      4.649473
21           -0.463445 -1.277444      0.494233
22           -0.536548 -0.957699     -0.494783
23           -0.430483 -0.573953     -0.817586
24           -0.329214 -0.338192     -0.845059

In [21]:
df_25_gb = pd.DataFrame(scaler.inverse_transform(df_25_norm_gb), columns=df_25_norm_gb.columns)
df_25_gb

Russia_MoM_predict         MoM  Russia_MoM-1
0            99.960952   99.337024        100.35
1            99.930655  100.570486         99.96
2           100.429929   99.910327         99.93
3           100.709649   97.395858        100.43
4           100.830290  101.445817        100.71
5           100.671249  101.144785        100.83
6           100.778556   99.449539        100.67
7           100.661060   99.582982        100.78
8           100.580975   99.711704        100.66
9           100.738978  100.894241        100.58
10          100.689258   98.932025        100.74
11          100.310754  100.771324        100.69
12          100.169570   99.910265        100.31
13          100.599786  101.387850        100.17
14          101.110140  103.915668        100.60
15          100.960585  102.798455        101.11
16          100.819596  101.004126        100.96
17          100.988765  102.137140        100.82
18          101.169022  100.120816        100.99
19          107.609502  106.746746        101.17
20          101.559887   97.438199        107.61
21          100.120843   97.832254        101.56
22          100.012830   98.473673        100.12
23          100.169545   99.243480         99.65
24          100.319175   99.716424         99.61

In [22]:
df_25_norm_train = df_25_norm.iloc[:-3]
df_25_norm_test = df_25_norm.iloc[-3:]
rf_25 = RandomForestRegressor(n_estimators = 100, max_depth = 9)
rf_25.fit(df_25_norm_train.iloc[:, 1:], df_25_norm_train.iloc[:, 0])
df_25_rf_predict = rf_25.predict(df_25_norm.iloc[:, 1:])
df_25_rf_predict

array([-0.49237379, -0.46523401, -0.3292644 , -0.15341984, -0.03167436,
       -0.05067897, -0.09871164, -0.11031654, -0.14043651, -0.07761796,
       -0.12560326, -0.25609077, -0.41954984, -0.24398729,  0.10361846,
        0.17826977,  0.03113291,  0.08920256,  0.08507407,  3.09122755,
        0.47613053, -0.01773222, -0.43017564, -0.38219035, -0.33515258])

In [23]:
rf_25.feature_importances_

array([0.72183727, 0.27816273])

In [24]:
df_25_norm_rf = pd.DataFrame({'Russia_MoM_predict': df_25_rf_predict, 'MoM': df_25_norm.iloc[:, 1], 'Russia_MoM-1': df_25_norm.iloc[:, 2]})
df_25_norm_rf

Russia_MoM_predict       MoM  Russia_MoM-1
0            -0.492374 -0.527321     -0.336815
1            -0.465234  0.087555     -0.604673
2            -0.329264 -0.241532     -0.625278
3            -0.153420 -1.494985     -0.281869
4            -0.031674  0.523904     -0.089561
5            -0.050679  0.373840     -0.007143
6            -0.098712 -0.471233     -0.117034
7            -0.110317 -0.404712     -0.041484
8            -0.140437 -0.340545     -0.123902
9            -0.077618  0.248945     -0.178847
10           -0.125603 -0.729212     -0.068956
11           -0.256091  0.187672     -0.103297
12           -0.419550 -0.241563     -0.364287
13           -0.243987  0.495008     -0.460442
14            0.103618  1.755115     -0.165111
15            0.178270  1.198189      0.185166
16            0.031133  0.303723      0.082143
17            0.089203  0.868526     -0.014011
18            0.085074 -0.136604      0.102748
19            3.091228  3.166397      0.226375
20            0.476131 -1.473878      4.649473
21           -0.017732 -1.277444      0.494233
22           -0.430176 -0.957699     -0.494783
23           -0.382190 -0.573953     -0.817586
24           -0.335153 -0.338192     -0.845059

In [25]:
df_25_rf = pd.DataFrame(scaler.inverse_transform(df_25_norm_rf), columns=df_25_norm_rf.columns)
df_25_rf

Russia_MoM_predict         MoM  Russia_MoM-1
0           100.078100   99.337024        100.35
1           100.118200  100.570486         99.96
2           100.319100   99.910327         99.93
3           100.578917   97.395858        100.43
4           100.758800  101.445817        100.71
5           100.730720  101.144785        100.83
6           100.659750   99.449539        100.67
7           100.642603   99.582982        100.78
8           100.598100   99.711704        100.66
9           100.690917  100.894241        100.58
10          100.620017   98.932025        100.74
11          100.427217  100.771324        100.69
12          100.185700   99.910265        100.31
13          100.445100  101.387850        100.17
14          100.958700  103.915668        100.60
15          101.069000  102.798455        101.11
16          100.851600  101.004126        100.96
17          100.937400  102.137140        100.82
18          100.931300  100.120816        100.99
19          105.373000  106.746746        101.17
20          101.509100   97.438199        107.61
21          100.779400   97.832254        101.56
22          100.170000   98.473673        100.12
23          100.240900   99.243480         99.65
24          100.310400   99.716424         99.61

In [26]:
scaler = preprocessing.StandardScaler()
names = df_13_mom.columns
df_13_norm = pd.DataFrame(scaler.fit_transform(df_13_mom), columns=names)
df_13_norm

Russia_MoM       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0    -0.448931 -0.365105 -1.907280     -0.418912     -1.111940
1    -0.233336  0.224650 -1.760327     -0.490500     -1.060631
2     0.022369  1.233588 -1.029559     -0.270621     -0.892710
3    -0.052838  0.787670  0.022118     -0.009834     -0.722456
4    -0.123032  0.071492 -0.065008     -0.086536     -0.659486
5    -0.037797  0.523717  0.130469     -0.158124     -0.661818
6     0.052452 -0.281067  0.266272     -0.071195     -0.582522
7     3.281359  2.363568  1.723373      0.020847     -0.484568
8     0.247992 -1.351791  1.228319      3.313926      1.273941
9    -0.474000 -1.194510  0.584412      0.220273      1.539817
10   -0.709650 -0.938498  0.489096     -0.516068      1.369563
11   -0.729705 -0.631242  0.178621     -0.756401      1.089694
12   -0.794885 -0.442473  0.139493     -0.776855      0.903115

In [27]:
df_13_norm_train = df_13_norm.iloc[:-3]
df_13_norm_test = df_13_norm.iloc[-3:]
gb_13 = GradientBoostingRegressor(n_estimators = 200, max_depth = 3)
gb_13.fit(df_13_norm_train.iloc[:, 1:], df_13_norm_train.iloc[:, 0])
df_13_gb_predict = gb_13.predict(df_13_norm.iloc[:, 1:])
df_13_gb_predict

array([-0.44893065, -0.2333359 ,  0.02236934, -0.05283807, -0.1230316 ,
       -0.03779657,  0.05245231,  3.28135894,  0.24799176, -0.47399973,
       -0.21719382, -0.26196065, -0.26196065])

In [28]:
gb_13.feature_importances_

array([0.40078644, 0.58417912, 0.00538005, 0.00965439])

In [29]:
df_13_norm_gb = pd.DataFrame({'Russia_MoM_predict': df_13_gb_predict, 'MoM': df_13_norm.iloc[:, 1], 'YoY': df_13_norm.iloc[:, 2], 'Russia_MoM-1': df_13_norm.iloc[:, 3], 'Russia_YoY-1': df_13_norm.iloc[:, 4]})
df_13_norm_gb

Russia_MoM_predict       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0            -0.448931 -0.365105 -1.907280     -0.418912     -1.111940
1            -0.233336  0.224650 -1.760327     -0.490500     -1.060631
2             0.022369  1.233588 -1.029559     -0.270621     -0.892710
3            -0.052838  0.787670  0.022118     -0.009834     -0.722456
4            -0.123032  0.071492 -0.065008     -0.086536     -0.659486
5            -0.037797  0.523717  0.130469     -0.158124     -0.661818
6             0.052452 -0.281067  0.266272     -0.071195     -0.582522
7             3.281359  2.363568  1.723373      0.020847     -0.484568
8             0.247992 -1.351791  1.228319      3.313926      1.273941
9            -0.474000 -1.194510  0.584412      0.220273      1.539817
10           -0.217194 -0.938498  0.489096     -0.516068      1.369563
11           -0.261961 -0.631242  0.178621     -0.756401      1.089694
12           -0.261961 -0.442473  0.139493     -0.776855      0.903115

In [30]:
df_13_gb = pd.DataFrame(scaler.inverse_transform(df_13_norm_gb), columns=df_13_norm_gb.columns)
df_13_gb

Russia_MoM_predict         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0           100.170000   99.910265   99.651411        100.31        106.46
1           100.600000  101.387850  100.461306        100.17        106.68
2           101.110000  103.915668  104.488735        100.60        107.40
3           100.960000  102.798455  110.284777        101.11        108.13
4           100.820000  101.004126  109.804602        100.96        108.40
5           100.990000  102.137140  110.881921        100.82        108.39
6           101.170000  100.120816  111.630367        100.99        108.73
7           107.610000  106.746746  119.660790        101.17        109.15
8           101.560000   97.438199  116.932430        107.61        116.69
9           100.120000   97.832254  113.383708        101.56        117.83
10          100.632195   98.473673  112.858401        100.12        117.10
11          100.542908   99.243480  111.147299         99.65        115.90
12          100.542908   99.716424  110.931656         99.61        115.10

In [31]:
df_13_norm_train = df_13_norm.iloc[:-3]
df_13_norm_test = df_13_norm.iloc[-3:]
rf_13 = RandomForestRegressor(n_estimators = 100, max_depth = 9)
rf_13.fit(df_13_norm_train.iloc[:, 1:], df_13_norm_train.iloc[:, 0])
df_13_rf_predict = rf_13.predict(df_13_norm.iloc[:, 1:])
df_13_rf_predict

array([-0.3234846 , -0.23148082, -0.04957907,  0.01394616, -0.09029137,
       -0.04837575, -0.05108322,  2.10130391,  0.62678661, -0.09831349,
       -0.04010293, -0.03995251, -0.04276026])

In [32]:
rf_13.feature_importances_

array([0.45022081, 0.29476519, 0.09738882, 0.15762519])

In [33]:
df_13_norm_rf = pd.DataFrame({'Russia_MoM_predict': df_13_rf_predict, 'MoM': df_13_norm.iloc[:, 1], 'YoY': df_13_norm.iloc[:, 2], 'Russia_MoM-1': df_13_norm.iloc[:, 3], 'Russia_YoY-1': df_13_norm.iloc[:, 4]})
df_13_norm_rf

Russia_MoM_predict       MoM       YoY  Russia_MoM-1  Russia_YoY-1
0            -0.323485 -0.365105 -1.907280     -0.418912     -1.111940
1            -0.231481  0.224650 -1.760327     -0.490500     -1.060631
2            -0.049579  1.233588 -1.029559     -0.270621     -0.892710
3             0.013946  0.787670  0.022118     -0.009834     -0.722456
4            -0.090291  0.071492 -0.065008     -0.086536     -0.659486
5            -0.048376  0.523717  0.130469     -0.158124     -0.661818
6            -0.051083 -0.281067  0.266272     -0.071195     -0.582522
7             2.101304  2.363568  1.723373      0.020847     -0.484568
8             0.626787 -1.351791  1.228319      3.313926      1.273941
9            -0.098313 -1.194510  0.584412      0.220273      1.539817
10           -0.040103 -0.938498  0.489096     -0.516068      1.369563
11           -0.039953 -0.631242  0.178621     -0.756401      1.089694
12           -0.042760 -0.442473  0.139493     -0.776855      0.903115

In [34]:
df_13_rf = pd.DataFrame(scaler.inverse_transform(df_13_norm_rf), columns=df_13_norm_rf.columns)
df_13_rf

Russia_MoM_predict         MoM         YoY  Russia_MoM-1  Russia_YoY-1
0             100.4202   99.910265   99.651411        100.31        106.46
1             100.6037  101.387850  100.461306        100.17        106.68
2             100.9665  103.915668  104.488735        100.60        107.40
3             101.0932  102.798455  110.284777        101.11        108.13
4             100.8853  101.004126  109.804602        100.96        108.40
5             100.9689  102.137140  110.881921        100.82        108.39
6             100.9635  100.120816  111.630367        100.99        108.73
7             105.2564  106.746746  119.660790        101.17        109.15
8             102.3155   97.438199  116.932430        107.61        116.69
9             100.8693   97.832254  113.383708        101.56        117.83
10            100.9854   98.473673  112.858401        100.12        117.10
11            100.9857   99.243480  111.147299         99.65        115.90
12            100.9801   99.716424  110.931656         99.61        115.10

In [35]:
fig1 = go.Figure()
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25_gb.iloc[:, 0], line_color="blue", name='Градиентный бустинг',)
)
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25_rf.iloc[:, 0], line_color="green", name='Случайный лес')
)
fig1.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[:, 0], y=df_25.iloc[:, 0], line_color="red", name='Фактические данные')
)
fig1.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>')

In [36]:
fig2 = go.Figure()
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_gb.iloc[:, 0], line_color="blue", name='Градиентный бустинг')
)
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_rf.iloc[:, 0], line_color="green", name='Случайный лес')
)
fig2.add_trace(
      go.Scatter(mode='lines+markers', x=cpi_russia.iloc[-len(df_13_gb):, 0], y=df_13_mom.iloc[:, 0], line_color="red", name='Фактические данные')
)
fig2.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>')

In [37]:
mean_absolute_error(df_25.iloc[-3:, 0], df_25_gb.iloc[-3:, 0])

0.5871836391099853

In [38]:
mean_absolute_error(df_25.iloc[-3:, 0], df_25_rf.iloc[-3:, 0])

0.6604333333333301

In [39]:
mean_absolute_error(df_13_mom.iloc[-3:, 0], df_13_gb.iloc[-3:, 0])

0.9926707220955961

In [40]:
mean_absolute_error(df_13_mom.iloc[-3:, 0], df_13_rf.iloc[-3:, 0])

1.4037333333333255

In [41]:
fig3 = px.scatter(x=df_25.iloc[:, 0], y=df_25.iloc[:, 1])
fig3.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>', 
                   xaxis_title="Инфляция товаров из онлайн магазинов", 
                   yaxis_title="Инфляция на товары и услуги в России")
fig3.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

In [42]:
fig3 = px.scatter(x=df_25.iloc[:, 0], y=df_25.iloc[:, 2])
fig3.update_layout(title_text='<b>Прогнозы инфляция, месяц к месяцу в %<b>', 
                   xaxis_title="Инфляция на товары и услуги в России за прошлый месяц", 
                   yaxis_title="Инфляция на товары и услуги в России")
fig3.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

In [43]:
df_25_nn = df_25.copy()
df_25_nn['Spread'] = abs(df_25['MoM'] - df_25['Russia_MoM-1'])
df_25_nn

Russia_MoM         MoM  Russia_MoM-1     Spread
0        99.96   99.337024        100.35   1.012976
1        99.93  100.570486         99.96   0.610486
2       100.43   99.910327         99.93   0.019673
3       100.71   97.395858        100.43   3.034142
4       100.83  101.445817        100.71   0.735817
5       100.67  101.144785        100.83   0.314785
6       100.78   99.449539        100.67   1.220461
7       100.66   99.582982        100.78   1.197018
8       100.58   99.711704        100.66   0.948296
9       100.74  100.894241        100.58   0.314241
10      100.69   98.932025        100.74   1.807975
11      100.31  100.771324        100.69   0.081324
12      100.17   99.910265        100.31   0.399735
13      100.60  101.387850        100.17   1.217850
14      101.11  103.915668        100.60   3.315668
15      100.96  102.798455        101.11   1.688455
16      100.82  101.004126        100.96   0.044126
17      100.99  102.137140        100.82   1.317140
18      101.17  100.120816        100.99   0.869184
19      107.61  106.746746        101.17   5.576746
20      101.56   97.438199        107.61  10.171801
21      100.12   97.832254        101.56   3.727746
22       99.65   98.473673        100.12   1.646327
23       99.61   99.243480         99.65   0.406520
24       99.48   99.716424         99.61   0.106424

In [528]:
class TheModelClass(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(TheModelClass, self).__init__()
        self.input_size = input_size
        self.l1 = nn.Linear(input_size, 2)
        self.f1 = nn.Tanh()
        self.l2 = nn.Linear(2, 1)
        
    def forward(self, x):
        out1 = self.l1(x)
        outf1 = self.f1(out1)
        out = self.l2(outf1)
        return out

In [529]:
model = TheModelClass(3, 1).to(torch.float64)
print(model)

TheModelClass(
  (l1): Linear(in_features=3, out_features=2, bias=True)
  (f1): Tanh()
  (l2): Linear(in_features=2, out_features=1, bias=True)
)


In [530]:
criterion = nn.L1Loss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

In [531]:
for i in iter(model.parameters()):
    print(i)

Parameter containing:
tensor([[-0.4053, -0.0009,  0.1677],
        [ 0.0267,  0.0869, -0.0054]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([ 0.3244, -0.2309], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.6820, -0.4777]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.0355], dtype=torch.float64, requires_grad=True)


In [532]:
train_dataset = torch.tensor(df_25_nn.iloc[:-3, :].reset_index(drop = True).to_numpy())
train_dataset

tensor([[9.9960e+01, 9.9337e+01, 1.0035e+02, 1.0130e+00],
        [9.9930e+01, 1.0057e+02, 9.9960e+01, 6.1049e-01],
        [1.0043e+02, 9.9910e+01, 9.9930e+01, 1.9673e-02],
        [1.0071e+02, 9.7396e+01, 1.0043e+02, 3.0341e+00],
        [1.0083e+02, 1.0145e+02, 1.0071e+02, 7.3582e-01],
        [1.0067e+02, 1.0114e+02, 1.0083e+02, 3.1478e-01],
        [1.0078e+02, 9.9450e+01, 1.0067e+02, 1.2205e+00],
        [1.0066e+02, 9.9583e+01, 1.0078e+02, 1.1970e+00],
        [1.0058e+02, 9.9712e+01, 1.0066e+02, 9.4830e-01],
        [1.0074e+02, 1.0089e+02, 1.0058e+02, 3.1424e-01],
        [1.0069e+02, 9.8932e+01, 1.0074e+02, 1.8080e+00],
        [1.0031e+02, 1.0077e+02, 1.0069e+02, 8.1324e-02],
        [1.0017e+02, 9.9910e+01, 1.0031e+02, 3.9973e-01],
        [1.0060e+02, 1.0139e+02, 1.0017e+02, 1.2179e+00],
        [1.0111e+02, 1.0392e+02, 1.0060e+02, 3.3157e+00],
        [1.0096e+02, 1.0280e+02, 1.0111e+02, 1.6885e+00],
        [1.0082e+02, 1.0100e+02, 1.0096e+02, 4.4126e-02],
        [1.009

In [533]:
test_dataset = torch.tensor(df_25_nn.iloc[-3:, :].reset_index(drop = True).to_numpy())
test_dataset

tensor([[ 99.6500,  98.4737, 100.1200,   1.6463],
        [ 99.6100,  99.2435,  99.6500,   0.4065],
        [ 99.4800,  99.7164,  99.6100,   0.1064]], dtype=torch.float64)

In [534]:
# train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
#                                            batch_size=len(train_dataset), 
#                                            shuffle=False)
# test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
#                                           batch_size=len(test_dataset),
#                                           shuffle=False)

In [535]:
optimizer.param_groups[0]['lr']

0.01

In [536]:
criterion(model(test_dataset[:,1:]), torch.unsqueeze(test_dataset[:,0], 1))

tensor(99.3402, dtype=torch.float64, grad_fn=<L1LossBackward0>)

In [537]:
with torch.no_grad():
    num_epochs = 1000000
    optimizer.param_groups[0]['lr'] = 0.1
    best_model = copy.deepcopy(model)
    best_loss_test = criterion(best_model(test_dataset[:,1:]), torch.unsqueeze(test_dataset[:,0], 1)).detach()
    i = 0
for epoch in range(num_epochs):
    outputs_train = model(train_dataset[:,1:])
    loss_train = criterion(outputs_train, torch.unsqueeze(train_dataset[:,0], 1))

    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()
    
    with torch.no_grad():
        loss_test = criterion(model(test_dataset[:,1:]), torch.unsqueeze(test_dataset[:,0], 1))
        best_loss_test = criterion(best_model(test_dataset[:,1:]), torch.unsqueeze(test_dataset[:,0], 1))
    
        if epoch == 0:
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_test:.4}], Test-Loss: [{loss_train:.4}]')
            
        if loss_test < best_loss_test - 1e-6:   
            best_model = copy.deepcopy(model)
            best_loss_test = loss_test
            i = 0
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_train:.4}], Test-Loss: [{loss_test:.4}]')
        else:
            i += 1

        if i == 1000 and optimizer.param_groups[0]['lr'] * 0.5 > 1e-12:
            optimizer.param_groups[0]['lr'] = optimizer.param_groups[0]['lr'] * 0.5
            learning_rate = optimizer.param_groups[0]['lr']
            print (f'Epoch [{epoch+1}], Learning Rate: [{learning_rate:.4}], Train-Loss: [{loss_train:.4}]')
            i = 0
        elif optimizer.param_groups[0]['lr'] * 0.5 < 1e-12:
            learning_rate = optimizer.param_groups[0]['lr']
            print(f"На {epoch+1} эпохе Learning Rate стал слишком мал - {learning_rate:.4}") 
            break
            
        if num_epochs == 100000 - 1:
            print("Все эпохи прошли")            
        
for parameter in best_model.named_parameters():
    print(parameter)

Epoch [1], Learning Rate: [0.1], Train-Loss: [99.04], Test-Loss: [100.7]
Epoch [1], Learning Rate: [0.1], Train-Loss: [100.7], Test-Loss: [99.04]
Epoch [2], Learning Rate: [0.1], Train-Loss: [100.4], Test-Loss: [98.47]
Epoch [3], Learning Rate: [0.1], Train-Loss: [99.86], Test-Loss: [97.66]
Epoch [4], Learning Rate: [0.1], Train-Loss: [99.05], Test-Loss: [96.63]
Epoch [5], Learning Rate: [0.1], Train-Loss: [98.02], Test-Loss: [95.4]
Epoch [6], Learning Rate: [0.1], Train-Loss: [96.79], Test-Loss: [93.99]
Epoch [7], Learning Rate: [0.1], Train-Loss: [95.38], Test-Loss: [92.43]
Epoch [8], Learning Rate: [0.1], Train-Loss: [93.82], Test-Loss: [90.72]
Epoch [9], Learning Rate: [0.1], Train-Loss: [92.11], Test-Loss: [88.88]
Epoch [10], Learning Rate: [0.1], Train-Loss: [90.27], Test-Loss: [86.93]
Epoch [11], Learning Rate: [0.1], Train-Loss: [88.32], Test-Loss: [84.87]
Epoch [12], Learning Rate: [0.1], Train-Loss: [86.26], Test-Loss: [82.71]
Epoch [13], Learning Rate: [0.1], Train-Loss: [84

In [548]:
with torch.no_grad():
    print(criterion(best_model(test_dataset[:,1:]), torch.unsqueeze(test_dataset[:,0], 1)))
    print(best_model(test_dataset[:,1:]))
    print(torch.unsqueeze(test_dataset[:,0], 1))

tensor(0.0723, dtype=torch.float64)
tensor([[99.5630],
        [99.5630],
        [99.5630]], dtype=torch.float64)
tensor([[99.6500],
        [99.6100],
        [99.4800]], dtype=torch.float64)


In [544]:
for parameter in best_model.named_parameters():
    print(parameter[1][0].detach().numpy())

[-0.40534079 -0.00094793  0.16773851]
0.3243893086910248
[-33.78977729  32.63001559]
33.14324887898745


In [545]:
torch.save(best_model, "NN_Linear_3_1.pth")

In [546]:
best_model = torch.load('NN_Linear_3_1.pth')

In [547]:
for parameter in best_model.named_parameters():
    print(parameter[1][0].detach().numpy())

[-0.40534079 -0.00094793  0.16773851]
0.3243893086910248
[-33.78977729  32.63001559]
33.14324887898745
